module.exports = {
  // Happy Heart Capsules
  "happy heart": "La Vedaa Happy Heart Capsules",
  "heart": "La Vedaa Happy Heart Capsules",
  "heart care": "La Vedaa Happy Heart Capsules",
  "cardio": "La Vedaa Happy Heart Capsules",
  "blood pressure": "La Vedaa Happy Heart Capsules",
  "cholesterol": "La Vedaa Happy Heart Capsules",
  "circulation": "La Vedaa Happy Heart Capsules",
  "bp": "La Vedaa Happy Heart Capsules",
  "blood pressure": "La Vedaa Happy Heart Capsules",
  "poor circulation": "La Vedaa Happy Heart Capsules",
  "heart health": "La Vedaa Happy Heart Capsules",
  "cardiac support": "La Vedaa Happy Heart Capsules",
  "reduce headache": "La Vedaa Happy Heart Capsules",
  "anxiety relief": "La Vedaa Happy Heart Capsules",
  "healthy circulation": "La Vedaa Happy Heart Capsules",
  "heart tonic": "La Vedaa Happy Heart Capsules",
  "cholesterol control": "La Vedaa Happy Heart Capsules",
  "heart rhythm": "La Vedaa Happy Heart Capsules",
  "mental stress": "La Vedaa Happy Heart Capsules",
  "cardiovascular wellness": "La Vedaa Happy Heart Capsules",
  "blood detox": "La Vedaa Happy Heart Capsules",
  "palpitations": "La Vedaa Happy Heart Capsules",
  "heart pain": "La Vedaa Happy Heart Capsules",
  "reduce inflammation": "La Vedaa Happy Heart Capsules",
  "stress relief": "La Vedaa Happy Heart Capsules",
  "anxiety": "La Vedaa Happy Heart Capsules",
  "stress heart": "La Vedaa Happy Heart Capsules",
  "heart health": "La Vedaa Happy Heart Capsules",
  "ayurvedic heart supplement": "La Vedaa Happy Heart Capsules",
  "natural heart care": "La Vedaa Happy Heart Capsules",
  "cardiovascular support": "La Vedaa Happy Heart Capsules",
  "support blood circulation": "La Vedaa Happy Heart Capsules",
  "heart circulation booster": "La Vedaa Happy Heart Capsules",
  "improve blood pressure": "La Vedaa Happy Heart Capsules",
  "reduce high blood pressure": "La Vedaa Happy Heart Capsules",
  "cholesterol support": "La Vedaa Happy Heart Capsules",
  "balance cholesterol levels": "La Vedaa Happy Heart Capsules",
  "emotional heart health": "La Vedaa Happy Heart Capsules",
  "reduce heart stress": "La Vedaa Happy Heart Capsules",
  "heart tonic": "La Vedaa Happy Heart Capsules",
  "arjun for heart": "La Vedaa Happy Heart Capsules",
  "arjuna capsules": "La Vedaa Happy Heart Capsules",
  "garlic for cholesterol": "La Vedaa Happy Heart Capsules",
  "garlic for heart": "La Vedaa Happy Heart Capsules",
  "brahmi for emotional balance": "La Vedaa Happy Heart Capsules",
  "tulsi for heart": "La Vedaa Happy Heart Capsules",
  "amla for heart health": "La Vedaa Happy Heart Capsules",
  "jatamansi for anxiety": "La Vedaa Happy Heart Capsules",
  "natural blood pressure support": "La Vedaa Happy Heart Capsules",
  "herbal BP capsule": "La Vedaa Happy Heart Capsules",
  "sarpagandha for blood pressure": "La Vedaa Happy Heart Capsules",
  "shilajit for heart": "La Vedaa Happy Heart Capsules",
  "reduce heart palpitations": "La Vedaa Happy Heart Capsules",
  "emotional wellness supplement": "La Vedaa Happy Heart Capsules",
  "stress and heart health": "La Vedaa Happy Heart Capsules",
  "mental calm for heart": "La Vedaa Happy Heart Capsules",
  "anti-anxiety heart capsule": "La Vedaa Happy Heart Capsules",
  "natural cholesterol remedy": "La Vedaa Happy Heart Capsules",
  "blood purifier capsule": "La Vedaa Happy Heart Capsules",
  "ayurvedic anti-cholesterol": "La Vedaa Happy Heart Capsules",
  "happy heart supplement": "La Vedaa Happy Heart Capsules",
  "digestive support for heart": "La Vedaa Happy Heart Capsules",
  "liver and heart detox": "La Vedaa Happy Heart Capsules",
  "blood flow support": "La Vedaa Happy Heart Capsules",
  "cardiac strength capsule": "La Vedaa Happy Heart Capsules",
  "daily heart care": "La Vedaa Happy Heart Capsules",
  "prevent heart disease naturally": "La Vedaa Happy Heart Capsules",
  "ayurvedic heart balance": "La Vedaa Happy Heart Capsules",
  "natural BP stabilizer": "La Vedaa Happy Heart Capsules",
  "reduce artery blockage": "La Vedaa Happy Heart Capsules",
  "control bad cholesterol": "La Vedaa Happy Heart Capsules",
  "anti-inflammatory for heart": "La Vedaa Happy Heart Capsules",
  "heart problem": "La Vedaa Happy Heart Capsules",
  "chest tightness": "La Vedaa Happy Heart Capsules",
  "chest heaviness": "La Vedaa Happy Heart Capsules",
  "high blood pressure": "La Vedaa Happy Heart Capsules",
  "low blood pressure": "La Vedaa Happy Heart Capsules",
  "irregular heartbeat": "La Vedaa Happy Heart Capsules",
  "heart palpitations": "La Vedaa Happy Heart Capsules",
  "weak heart": "La Vedaa Happy Heart Capsules",
  "heart blockage": "La Vedaa Happy Heart Capsules",
  "heart pain": "La Vedaa Happy Heart Capsules",
  "heart fluttering": "La Vedaa Happy Heart Capsules",
  "shortness of breath": "La Vedaa Happy Heart Capsules",
  "poor blood circulation": "La Vedaa Happy Heart Capsules",
  "clogged arteries": "La Vedaa Happy Heart Capsules",
  "artery health": "La Vedaa Happy Heart Capsules",
  "heart inflammation": "La Vedaa Happy Heart Capsules",
  "stress-induced heart issues": "La Vedaa Happy Heart Capsules",
  "emotional heart problems": "La Vedaa Happy Heart Capsules",
  "cholesterol imbalance": "La Vedaa Happy Heart Capsules",
  "bad cholesterol": "La Vedaa Happy Heart Capsules",
  "LDL cholesterol": "La Vedaa Happy Heart Capsules",
  "high triglycerides": "La Vedaa Happy Heart Capsules",
  "heart rhythm disorder": "La Vedaa Happy Heart Capsules",
  "nervous heart": "La Vedaa Happy Heart Capsules",
  "ayurvedic remedy for heart": "La Vedaa Happy Heart Capsules",
  "natural heart support": "La Vedaa Happy Heart Capsules",
  "heart weakness solution": "La Vedaa Happy Heart Capsules",
  "herbal medicine for heart": "La Vedaa Happy Heart Capsules",
  "natural cure for high BP": "La Vedaa Happy Heart Capsules",
  "natural remedy for palpitations": "La Vedaa Happy Heart Capsules",
  "emotional stress and heart": "La Vedaa Happy Heart Capsules",
  "blood pressure stabilizer": "La Vedaa Happy Heart Capsules",
  "ayurvedic medicine for blood pressure": "La Vedaa Happy Heart Capsules",
  "natural cardiac care": "La Vedaa Happy Heart Capsules",
  "reduce heart risk": "La Vedaa Happy Heart Capsules",
  "prevent heart attack naturally": "La Vedaa Happy Heart Capsules",
  "chest pain due to anxiety": "La Vedaa Happy Heart Capsules",
  "heart rate anxiety remedy": "La Vedaa Happy Heart Capsules",
  "herbs to lower blood pressure": "La Vedaa Happy Heart Capsules",
  "natural heart support supplement": "La Vedaa Happy Heart Capsules",
  "natural remedy for heart palpitations": "La Vedaa Happy Heart Capsules",
  "how to reduce high blood pressure naturally": "La Vedaa Happy Heart Capsules",
  "ayurvedic herbs for heart health": "La Vedaa Happy Heart Capsules",
  "best natural supplement for heart health": "La Vedaa Happy Heart Capsules",
  "stress relief for heart patients": "La Vedaa Happy Heart Capsules",
  "herbal medicine for cholesterol control": "La Vedaa Happy Heart Capsules",
  "natural ways to improve blood circulation": "La Vedaa Happy Heart Capsules",
  "reduce bad cholesterol naturally": "La Vedaa Happy Heart Capsules",
  "ayurvedic treatment for heart problems": "La Vedaa Happy Heart Capsules",
  "how to manage heart palpitations naturally": "La Vedaa Happy Heart Capsules",
  "foods and herbs for healthy heart": "La Vedaa Happy Heart Capsules",
  "supplements to strengthen heart muscles": "La Vedaa Happy Heart Capsules",
  "herbal capsules for blood pressure balance": "La Vedaa Happy Heart Capsules",
  "natural cardiac care for adults": "La Vedaa Happy Heart Capsules",
  "remedies for irregular heartbeat": "La Vedaa Happy Heart Capsules",
  "herbal support for emotional heart health": "La Vedaa Happy Heart Capsules",
  "prevent heart attack naturally with herbs": "La Vedaa Happy Heart Capsules",
  "how to lower cholesterol naturally": "La Vedaa Happy Heart Capsules",
  "natural anti-inflammatory for heart health": "La Vedaa Happy Heart Capsules",
  "best ayurvedic capsules for heart health": "La Vedaa Happy Heart Capsules",
  "herbal stress relief for heart health": "La Vedaa Happy Heart Capsules",
  "heart palpitations causes and remedies": "La Vedaa Happy Heart Capsules",
  "natural ways to reduce heart inflammation": "La Vedaa Happy Heart Capsules",
  "how to strengthen weak heart muscles": "La Vedaa Happy Heart Capsules",
  "ayurvedic remedies for high blood pressure": "La Vedaa Happy Heart Capsules",
  "natural supplements to improve circulation": "La Vedaa Happy Heart Capsules",
  "herbal supplements for healthy blood pressure": "La Vedaa Happy Heart Capsules",
  "foods that help reduce cholesterol": "La Vedaa Happy Heart Capsules",
  "natural heart tonic for daily use": "La Vedaa Happy Heart Capsules",
  "how to calm heart anxiety naturally": "La Vedaa Happy Heart Capsules",
  "best herbs for heart rhythm balance": "La Vedaa Happy Heart Capsules",
  "reduce oxidative stress in heart": "La Vedaa Happy Heart Capsules",
  "improve artery flexibility naturally": "La Vedaa Happy Heart Capsules",
  "herbal blood purifier for heart health": "La Vedaa Happy Heart Capsules",
  "manage water retention for heart health": "La Vedaa Happy Heart Capsules",
  "natural remedy for heart stress": "La Vedaa Happy Heart Capsules",
  "ayurvedic capsules to support heart function": "La Vedaa Happy Heart Capsules",
  "natural ways to prevent heart disease": "La Vedaa Happy Heart Capsules",
  "herbal treatment for heart palpitations": "La Vedaa Happy Heart Capsules",
  "how to balance cholesterol with herbs": "La Vedaa Happy Heart Capsules",
  "natural supplements to improve heart endurance": "La Vedaa Happy Heart Capsules",
  "reduce heart-related mental stress": "La Vedaa Happy Heart Capsules",
  "herbal solution for healthy blood flow": "La Vedaa Happy Heart Capsules",
  "ayurvedic herbs for cardiac strength": "La Vedaa Happy Heart Capsules",
  "how to detox blood for better heart health": "La Vedaa Happy Heart Capsules",
  "natural support for nervous system and heart": "La Vedaa Happy Heart Capsules",
  "heart care supplements for men and women": "La Vedaa Happy Heart Capsules",
  "best herbal capsules for blood pressure": "La Vedaa Happy Heart Capsules",
  "natural heart support without side effects": "La Vedaa Happy Heart Capsules",
  "ayurvedic remedy for emotional heart issues": "La Vedaa Happy Heart Capsules",
  "how to improve heart health with herbs": "La Vedaa Happy Heart Capsules",
  "best supplements to prevent heart diseases": "La Vedaa Happy Heart Capsules",
  "high blood pressure causes": "La Vedaa Happy Heart Capsules",
  "how to reduce high blood pressure naturally": "La Vedaa Happy Heart Capsules",
  "causes of bad cholesterol": "La Vedaa Happy Heart Capsules",
  "natural ways to reduce heart inflammation": "La Vedaa Happy Heart Capsules",
  "oxidative stress in heart causes": "La Vedaa Happy Heart Capsules",
  "water retention causes in heart patients": "La Vedaa Happy Heart Capsules",
  "emotional stress effects on heart": "La Vedaa Happy Heart Capsules",
  "causes of weak heart muscles": "La Vedaa Happy Heart Capsules",

  // Men Care Capsules
  "energy": "La Vedaa Men Care Capsules",
  "strength": "La Vedaa Men Care Capsules",
  "vitality": "La Vedaa Men Care Capsules",
  "testosterone": "La Vedaa Men Care Capsules",
  "libido": "La Vedaa Men Care Capsules",
  "recovery": "La Vedaa Men Care Capsules",
  "performance": "La Vedaa Men Care Capsules",
  "endurance": "La Vedaa Men Care Capsules",
  "wellness": "La Vedaa Men Care Capsules",
  "fertility": "La Vedaa Men Care Capsules",
  "stress": "La Vedaa Men Care Capsules",
  "anxiety": "La Vedaa Men Care Capsules",
  "muscle": "La Vedaa Men Care Capsules",
  "nervous": "La Vedaa Men Care Capsules",
  "strengthening": "La Vedaa Men Care Capsules",
  "balance": "La Vedaa Men Care Capsules",
  "emotional": "La Vedaa Men Care Capsules",
  "reproductive": "La Vedaa Men Care Capsules",
  "hormones": "La Vedaa Men Care Capsules",
  "immunity": "La Vedaa Men Care Capsules",
  "fatigue": "La Vedaa Men Care Capsules",
  "vigor": "La Vedaa Men Care Capsules",
  "libidinal": "La Vedaa Men Care Capsules",
  "renewal": "La Vedaa Men Care Capsules",
  "endocrine": "La Vedaa Men Care Capsules",
  "drive": "La Vedaa Men Care Capsules",
  "potency": "La Vedaa Men Care Capsules",
  "male": "La Vedaa Men Care Capsules",
  "performance": "La Vedaa Men Care Capsules",
  "rejuvenation": "La Vedaa Men Care Capsules",
  "resilience": "La Vedaa Men Care Capsules",
  "male stamina": "La Vedaa Men Care Capsules",
  "energy booster": "La Vedaa Men Care Capsules",
  "testosterone support": "La Vedaa Men Care Capsules",
  "male vitality": "La Vedaa Men Care Capsules",
  "sexual health": "La Vedaa Men Care Capsules",
  "male strength": "La Vedaa Men Care Capsules",
  "libido enhancer": "La Vedaa Men Care Capsules",
  "stress relief": "La Vedaa Men Care Capsules",
  "muscle strength": "La Vedaa Men Care Capsules",
  "physical endurance": "La Vedaa Men Care Capsules",
  "reproductive health": "La Vedaa Men Care Capsules",
  "hormonal balance": "La Vedaa Men Care Capsules",
  "mental strength": "La Vedaa Men Care Capsules",
  "emotional balance": "La Vedaa Men Care Capsules",
  "energy levels": "La Vedaa Men Care Capsules",
  "fatigue relief": "La Vedaa Men Care Capsules",
  "immune support": "La Vedaa Men Care Capsules",
  "performance booster": "La Vedaa Men Care Capsules",
  "body recovery": "La Vedaa Men Care Capsules",
  "male wellness": "La Vedaa Men Care Capsules",
  "sexual stamina": "La Vedaa Men Care Capsules",
  "natural energy": "La Vedaa Men Care Capsules",
  "strength booster": "La Vedaa Men Care Capsules",
  "stress management": "La Vedaa Men Care Capsules",
  "physical strength": "La Vedaa Men Care Capsules",
  "muscle recovery": "La Vedaa Men Care Capsules",
  "reproductive strength": "La Vedaa Men Care Capsules",
  "male hormone": "La Vedaa Men Care Capsules",
  "herbal tonic": "La Vedaa Men Care Capsules",
  "nervous system": "La Vedaa Men Care Capsules",
  "boost male stamina": "La Vedaa Men Care Capsules",
  "support testosterone levels": "La Vedaa Men Care Capsules",
  "enhance male vitality": "La Vedaa Men Care Capsules",
  "natural energy booster": "La Vedaa Men Care Capsules",
  "improve sexual health": "La Vedaa Men Care Capsules",
  "reduce stress anxiety": "La Vedaa Men Care Capsules",
  "strengthen muscle recovery": "La Vedaa Men Care Capsules",
  "promote hormonal balance": "La Vedaa Men Care Capsules",
  "support reproductive health": "La Vedaa Men Care Capsules",
  "increase physical endurance": "La Vedaa Men Care Capsules",
  "enhance mental strength": "La Vedaa Men Care Capsules",
  "boost libido naturally": "La Vedaa Men Care Capsules",
  "improve emotional balance": "La Vedaa Men Care Capsules",
  "natural male wellness": "La Vedaa Men Care Capsules",
  "herbal stamina booster": "La Vedaa Men Care Capsules",
  "strengthen nervous system": "La Vedaa Men Care Capsules",
  "reduce physical fatigue": "La Vedaa Men Care Capsules",
  "support immune system": "La Vedaa Men Care Capsules",
  "promote healthy hormones": "La Vedaa Men Care Capsules",
  "increase male performance": "La Vedaa Men Care Capsules",
  "men health": "La Vedaa Men Care Capsules",
  "recovery": "La Vedaa Men Care Capsules",
  "mens capsule": "La Vedaa Men Care Capsules",
  "low stamina in men": "La Vedaa Men Care Capsules",
  "male fatigue solutions": "La Vedaa Men Care Capsules",
  "lack of energy in men": "La Vedaa Men Care Capsules",
  "reduced male libido": "La Vedaa Men Care Capsules",
  "male hormonal imbalance symptoms": "La Vedaa Men Care Capsules",
  "stress and anxiety in men": "La Vedaa Men Care Capsules",
  "poor physical performance in men": "La Vedaa Men Care Capsules",
  "low testosterone symptoms": "La Vedaa Men Care Capsules",
  "muscle weakness in men": "La Vedaa Men Care Capsules",
  "emotional fatigue in men": "La Vedaa Men Care Capsules",
  "causes of low testosterone": "La Vedaa Men Care Capsules",
  "effects of stress on male hormones": "La Vedaa Men Care Capsules",
  "reasons for male infertility": "La Vedaa Men Care Capsules",
  "causes of low male libido": "La Vedaa Men Care Capsules",
  "reasons for male fatigue": "La Vedaa Men Care Capsules",
  "effects of poor diet on male health": "La Vedaa Men Care Capsules",
  "impact of lifestyle on male vitality": "La Vedaa Men Care Capsules",
  "causes of weak muscles in men": "La Vedaa Men Care Capsules",
  "stress-related male health issues": "La Vedaa Men Care Capsules",
  "best herbal capsules for men energy": "La Vedaa Men Care Capsules",
  "natural testosterone boosters for men": "La Vedaa Men Care Capsules",
  "herbal supplements for male stamina": "La Vedaa Men Care Capsules",
  "ayurvedic medicine for male vitality": "La Vedaa Men Care Capsules",
  "natural ways to improve male libido": "La Vedaa Men Care Capsules",
  "herbs to reduce male stress and anxiety": "La Vedaa Men Care Capsules",
  "supplements to enhance male physical strength": "La Vedaa Men Care Capsules",
  "improve male reproductive health naturally": "La Vedaa Men Care Capsules",
  "best ayurvedic supplement for men’s wellness": "La Vedaa Men Care Capsules",
  "natural male hormone balance support": "La Vedaa Men Care Capsules",
  "herbal energy boosters for men": "La Vedaa Men Care Capsules",
  "natural ways to improve male endurance": "La Vedaa Men Care Capsules",
  "ayurvedic solution for male hormonal health": "La Vedaa Men Care Capsules",
  "herbal treatment for male sexual health": "La Vedaa Men Care Capsules",
  "boost male energy and strength naturally": "La Vedaa Men Care Capsules",
  "natural supplement to improve male mood": "La Vedaa Men Care Capsules",
  "support male muscle recovery naturally": "La Vedaa Men Care Capsules",
  "best supplements for male reproductive strength": "La Vedaa Men Care Capsules",
  "herbal remedy for male fatigue and stress": "La Vedaa Men Care Capsules",
  "natural tonic for male vitality and wellness": "La Vedaa Men Care Capsules",
  "ayurvedic capsules to enhance male performance": "La Vedaa Men Care Capsules",
  "herbs to improve male physical endurance": "La Vedaa Men Care Capsules",
  "support male nervous system health": "La Vedaa Men Care Capsules",
  "natural remedies for male emotional health": "La Vedaa Men Care Capsules",
  "ayurvedic supplement for male stamina and strength": "La Vedaa Men Care Capsules",
  "natural supplement for healthy male hormones": "La Vedaa Men Care Capsules",
  "herbal capsules to boost male libido and vitality": "La Vedaa Men Care Capsules",
  "ayurvedic energy booster for men": "La Vedaa Men Care Capsules",
  "herbal support for male reproductive system": "La Vedaa Men Care Capsules",
  "natural capsules to improve male confidence": "La Vedaa Men Care Capsules",
  "best herbs for male physical and emotional wellness": "La Vedaa Men Care Capsules",

  // Deep Sleep Capsules
  "sleep": "La Vedaa Deep Sleep Capsules",
  "deep sleep": "La Vedaa Deep Sleep Capsules",
  "insomnia": "La Vedaa Deep Sleep Capsules",
  "relax": "La Vedaa Deep Sleep Capsules",
  "anxiety": "La Vedaa Deep Sleep Capsules",
  "calm": "La Vedaa Deep Sleep Capsules",
  "sleep aid": "La Vedaa Deep Sleep Capsules",
  "non habit sleep": "La Vedaa Deep Sleep Capsules",
  "head pain": "La Vedaa Deep Sleep Capsules",
  "headache": "La Vedaa Deep Sleep Capsules",
  "migraine": "La Vedaa Deep Sleep Capsules",
  "sleep problem": "La Vedaa Deep Sleep Capsules",
  "trouble sleeping": "La Vedaa Deep Sleep Capsules",
  "can't sleep": "La Vedaa Deep Sleep Capsules",
  "poor sleep": "La Vedaa Deep Sleep Capsules",
  "mental fatigue": "La Vedaa Deep Sleep Capsules",
  "feel tired": "La Vedaa Deep Sleep Capsules",
  "brain tired": "La Vedaa Deep Sleep Capsules",
  "stress sleep": "La Vedaa Deep Sleep Capsules",
  "sleep aid without side effects": "La Vedaa Deep Sleep Capsules",
  "natural sleep supplement": "La Vedaa Deep Sleep Capsules",
  "ayurvedic sleep remedy": "La Vedaa Deep Sleep Capsules",
  "deep sleep support": "La Vedaa Deep Sleep Capsules",
  "fall asleep fast naturally": "La Vedaa Deep Sleep Capsules",
  "remedy for sleeplessness": "La Vedaa Deep Sleep Capsules",
  "night time relaxation capsules": "La Vedaa Deep Sleep Capsules",
  "herbal sleeping pills": "La Vedaa Deep Sleep Capsules",
  "non habit forming sleep medicine": "La Vedaa Deep Sleep Capsules",
  "bedtime stress relief": "La Vedaa Deep Sleep Capsules",
  "sleep better at night": "La Vedaa Deep Sleep Capsules",
  "stress relief supplement": "La Vedaa Deep Sleep Capsules",
  "anxiety relief capsules": "La Vedaa Deep Sleep Capsules",
  "calm mind naturally": "La Vedaa Deep Sleep Capsules",
  "natural anti-anxiety pills": "La Vedaa Deep Sleep Capsules",
  "reduce cortisol naturally": "La Vedaa Deep Sleep Capsules",
  "relaxation capsules": "La Vedaa Deep Sleep Capsules",
  "emotional balance supplement": "La Vedaa Deep Sleep Capsules",
  "feel refreshed in morning": "La Vedaa Deep Sleep Capsules",
  "mental exhaustion relief": "La Vedaa Deep Sleep Capsules",
  "increase daytime energy": "La Vedaa Deep Sleep Capsules",
  "restore body energy": "La Vedaa Deep Sleep Capsules",
  "wake up refreshed": "La Vedaa Deep Sleep Capsules",
  "brain fog remedy": "La Vedaa Deep Sleep Capsules",
  "daytime alertness": "La Vedaa Deep Sleep Capsules",
  "shift workers sleep aid": "La Vedaa Deep Sleep Capsules",
  "insomnia remedy for adults": "La Vedaa Deep Sleep Capsules",
  "jet lag natural cure": "La Vedaa Deep Sleep Capsules",
  "students sleep support": "La Vedaa Deep Sleep Capsules",
  "postpartum sleep support": "La Vedaa Deep Sleep Capsules",
  "sleepless nights solution": "La Vedaa Deep Sleep Capsules",
  "Ashwagandha for sleep": "La Vedaa Deep Sleep Capsules",
  "Tagar benefits for insomnia": "La Vedaa Deep Sleep Capsules",
  "Jatamansi sleep capsule": "La Vedaa Deep Sleep Capsules",
  "Rudraksha calming effect": "La Vedaa Deep Sleep Capsules",
  "Sarpagandha ayurvedic use": "La Vedaa Deep Sleep Capsules",
  "La Vedaa capsules review": "La Vedaa Deep Sleep Capsules",
  "La Vedaa sleep supplement": "La Vedaa Deep Sleep Capsules",
  "La Vedaa Ayurveda sleep": "La Vedaa Deep Sleep Capsules",
  "non addictive sleep capsules": "La Vedaa Deep Sleep Capsules",
  "vegetarian ayurvedic sleep pills": "La Vedaa Deep Sleep Capsules",
  "neend nahi aati": "La Vedaa Deep Sleep Capsules",
  "neend ki dawai ayurvedic": "La Vedaa Deep Sleep Capsules",
  "thakan aur neend ke liye goli": "La Vedaa Deep Sleep Capsules",
  "achhi neend ke liye kya lein": "La Vedaa Deep Sleep Capsules",
  "natural cure for insomnia": "La Vedaa Deep Sleep Capsules",
  "best ayurvedic sleep capsules": "La Vedaa Deep Sleep Capsules",
  "herbal medicine for sleep": "La Vedaa Deep Sleep Capsules",
  "sleep improvement supplement": "La Vedaa Deep Sleep Capsules",
  "natural night time relaxant": "La Vedaa Deep Sleep Capsules",
  "sleeping disorder solution": "La Vedaa Deep Sleep Capsules",
  "calm body and mind": "La Vedaa Deep Sleep Capsules",
  "relaxation before bedtime": "La Vedaa Deep Sleep Capsules",
  "ayurvedic solution for stress": "La Vedaa Deep Sleep Capsules",
  "natural remedy for overthinking": "La Vedaa Deep Sleep Capsules",




  // Women Care Capsules
  "hormones": "La Vedaa Women Care Capsules",
  "menstruation": "La Vedaa Women Care Capsules",
  "digestion": "La Vedaa Women Care Capsules",
  "metabolism": "La Vedaa Women Care Capsules",
  "skin": "La Vedaa Women Care Capsules",
  "hair": "La Vedaa Women Care Capsules",
  "stress": "La Vedaa Women Care Capsules",
  "mood": "La Vedaa Women Care Capsules",
  "fertility": "La Vedaa Women Care Capsules",
  "cramps": "La Vedaa Women Care Capsules",
  "abdominal": "La Vedaa Women Care Capsules",
  "discomfort": "La Vedaa Women Care Capsules",
  "immunity": "La Vedaa Women Care Capsules",
  "inflammation": "La Vedaa Women Care Capsules",
  "wellness": "La Vedaa Women Care Capsules",
  "reproductive": "La Vedaa Women Care Capsules",
  "balance": "La Vedaa Women Care Capsules",
  "energy": "La Vedaa Women Care Capsules",
  "vitality": "La Vedaa Women Care Capsules",
  "detox": "La Vedaa Women Care Capsules",
  "fibroids": "La Vedaa Women Care Capsules",
  "hormonal balance": "La Vedaa Women Care Capsules",
  "menstrual health": "La Vedaa Women Care Capsules",
  "menstrual cramps": "La Vedaa Women Care Capsules",
  "digestive health": "La Vedaa Women Care Capsules",
  "skin health": "La Vedaa Women Care Capsules",
  "hair health": "La Vedaa Women Care Capsules",
  "stress relief": "La Vedaa Women Care Capsules",
  "emotional balance": "La Vedaa Women Care Capsules",
  "uterine health": "La Vedaa Women Care Capsules",
  "abdominal pain": "La Vedaa Women Care Capsules",
  "female vitality": "La Vedaa Women Care Capsules",
  "reproductive wellness": "La Vedaa Women Care Capsules",
  "menstrual irregularities": "La Vedaa Women Care Capsules",
  "white discharge": "La Vedaa Women Care Capsules",
  "pelvic muscles": "La Vedaa Women Care Capsules",
  "immune support": "La Vedaa Women Care Capsules",
  "natural glow": "La Vedaa Women Care Capsules",
  "energy boost": "La Vedaa Women Care Capsules",
  "calm mind": "La Vedaa Women Care Capsules",
  "inflammation relief": "La Vedaa Women Care Capsules",
  "uterus tone": "La Vedaa Women Care Capsules",
  "balance female hormones": "La Vedaa Women Care Capsules",
  "regulate menstrual cycles": "La Vedaa Women Care Capsules",
  "ease menstrual cramps": "La Vedaa Women Care Capsules",
  "boost digestive metabolism": "La Vedaa Women Care Capsules",
  "improve hair health": "La Vedaa Women Care Capsules",
  "reduce emotional stress": "La Vedaa Women Care Capsules",
  "soothe abdominal discomfort": "La Vedaa Women Care Capsules",
  "enhance skin glow": "La Vedaa Women Care Capsules",
  "strengthen pelvic muscles": "La Vedaa Women Care Capsules",
  "support reproductive health": "La Vedaa Women Care Capsules",
  "relieve menstrual pain": "La Vedaa Women Care Capsules",
  "natural hormonal support": "La Vedaa Women Care Capsules",
  "detoxify female body": "La Vedaa Women Care Capsules",
  "improve mood swings": "La Vedaa Women Care Capsules",
  "reduce white discharge": "La Vedaa Women Care Capsules",
  "calm mental fatigue": "La Vedaa Women Care Capsules",
  "promote uterine health": "La Vedaa Women Care Capsules",
  "support female fertility": "La Vedaa Women Care Capsules",
  "boost female vitality": "La Vedaa Women Care Capsules",
  "soothe inflammation naturally": "La Vedaa Women Care Capsules",
  "menstrual cramps": "La Vedaa Women Care Capsules",
  "irregular periods": "La Vedaa Women Care Capsules",
  "abdominal pain": "La Vedaa Women Care Capsules",
  "white discharge": "La Vedaa Women Care Capsules",
  "mood swings": "La Vedaa Women Care Capsules",
  "mental fatigue": "La Vedaa Women Care Capsules",
  "skin dullness": "La Vedaa Women Care Capsules",
  "hair fall": "La Vedaa Women Care Capsules",
  "bloating": "La Vedaa Women Care Capsules",
  "emotional stress": "La Vedaa Women Care Capsules",
  "hormonal imbalance": "La Vedaa Women Care Capsules",
  "stress and anxiety": "La Vedaa Women Care Capsules",
  "poor digestion": "La Vedaa Women Care Capsules",
  "nutritional deficiency": "La Vedaa Women Care Capsules",
  "inflammation": "La Vedaa Women Care Capsules",
  "uterine issues": "La Vedaa Women Care Capsules",
  "immune weakness": "La Vedaa Women Care Capsules",
  "fatigue and exhaustion": "La Vedaa Women Care Capsules",
  "balance hormones naturally": "La Vedaa Women Care Capsules",
  "relieve menstrual cramps": "La Vedaa Women Care Capsules",
  "improve digestion health": "La Vedaa Women Care Capsules",
  "boost skin glow": "La Vedaa Women Care Capsules",
  "reduce emotional stress": "La Vedaa Women Care Capsules",
  "strengthen hair roots": "La Vedaa Women Care Capsules",
  "support immune system": "La Vedaa Women Care Capsules",
  "enhance reproductive health": "La Vedaa Women Care Capsules",
  "calm mental fatigue": "La Vedaa Women Care Capsules",
  "natural hormonal support": "La Vedaa Women Care Capsules",
  "ease abdominal pain": "La Vedaa Women Care Capsules",
  "promote uterine health": "La Vedaa Women Care Capsules",
  "boost female vitality": "La Vedaa Women Care Capsules",
  "reduce inflammation naturally": "La Vedaa Women Care Capsules",
  "improve mood balance": "La Vedaa Women Care Capsules",
  "PCOD": "La Vedaa Women Care Capsules",
  "PCOS": "La Vedaa Women Care Capsules",
  "fibroids": "La Vedaa Women Care Capsules",
  "endometriosis": "La Vedaa Women Care Capsules",
  "menopause": "La Vedaa Women Care Capsules",
  "anemia": "La Vedaa Women Care Capsules",
  "infertility": "La Vedaa Women Care Capsules",
  "bloating": "La Vedaa Women Care Capsules",
  "premenstrual": "La Vedaa Women Care Capsules",
  "irregularity": "La Vedaa Women Care Capsules",
  "polycystic ovary": "La Vedaa Women Care Capsules",
  "ovarian cysts": "La Vedaa Women Care Capsules",
  "menstrual irregularities": "La Vedaa Women Care Capsules",
  "endometriosis pain": "La Vedaa Women Care Capsules",
  "fibroid tumors": "La Vedaa Women Care Capsules",
  "menstrual bleeding": "La Vedaa Women Care Capsules",
  "premenstrual syndrome": "La Vedaa Women Care Capsules",
  "menopausal symptoms": "La Vedaa Women Care Capsules",
  "low libido": "La Vedaa Women Care Capsules",
  "heavy bleeding": "La Vedaa Women Care Capsules",
  "manage polycystic ovary": "La Vedaa Women Care Capsules",
  "relieve fibroid symptoms": "La Vedaa Women Care Capsules",
  "reduce endometriosis pain": "La Vedaa Women Care Capsules",
  "balance hormones PCOS": "La Vedaa Women Care Capsules",
  "control menstrual irregularities": "La Vedaa Women Care Capsules",
  "support menopausal health": "La Vedaa Women Care Capsules",
  "ease premenstrual syndrome": "La Vedaa Women Care Capsules",
  "improve female fertility": "La Vedaa Women Care Capsules",
  "reduce heavy menstrual bleeding": "La Vedaa Women Care Capsules",
  "soothe menstrual pain naturally": "La Vedaa Women Care Capsules",
  "irregular periods": "La Vedaa Women Care Capsules",
  "heavy menstrual bleeding": "La Vedaa Women Care Capsules",
  "pelvic pain": "La Vedaa Women Care Capsules",
  "abdominal bloating": "La Vedaa Women Care Capsules",
  "mood swings": "La Vedaa Women Care Capsules",
  "hair thinning": "La Vedaa Women Care Capsules",
  "fatigue": "La Vedaa Women Care Capsules",
  "low libido": "La Vedaa Women Care Capsules",
  "weight gain": "La Vedaa Women Care Capsules",
  "acne": "La Vedaa Women Care Capsules",
  "balance hormones PCOD": "La Vedaa Women Care Capsules",
  "reduce fibroid size": "La Vedaa Women Care Capsules",
  "ease endometriosis symptoms": "La Vedaa Women Care Capsules",
  "support healthy menstrual cycle": "La Vedaa Women Care Capsules",
  "manage menopausal symptoms": "La Vedaa Women Care Capsules",
  "improve fertility naturally": "La Vedaa Women Care Capsules",
  "reduce menstrual pain": "La Vedaa Women Care Capsules",
  "promote hormonal balance": "La Vedaa Women Care Capsules",
  "natural relief PCOS": "La Vedaa Women Care Capsules",
  "control menstrual bleeding": "La Vedaa Women Care Capsules",
  "period": "La Vedaa Women Care Capsules",


  // Energy Booster Capsules
  "energy": "La Vedaa Energy Booster Capsules",
  "booster": "La Vedaa Energy Booster Capsules",
  "fatigue": "La Vedaa Energy Booster Capsules",
  "tiredness": "La Vedaa Energy Booster Capsules",
  "energy pills": "La Vedaa Energy Booster Capsules",
  "boost stamina": "La Vedaa Energy Booster Capsules",
  "energy support": "La Vedaa Energy Booster Capsules",
  "body energy": "La Vedaa Energy Booster Capsules",

  "natural energy supplement": "La Vedaa Energy Booster Capsules",
  "herbal energy capsule": "La Vedaa Energy Booster Capsules",
  "ayurvedic multivitamin": "La Vedaa Energy Booster Capsules",
  "natural stamina booster": "La Vedaa Energy Booster Capsules",
  "non caffeine energy booster": "La Vedaa Energy Booster Capsules",
  "physical strength capsule": "La Vedaa Energy Booster Capsules",
  "ashwagandha for energy": "La Vedaa Energy Booster Capsules",
  "shilajit capsule": "La Vedaa Energy Booster Capsules",
  "salam panja benefits": "La Vedaa Energy Booster Capsules",
  "endurance supplement": "La Vedaa Energy Booster Capsules",
  "energy for gym": "La Vedaa Energy Booster Capsules",
  "daily energy support": "La Vedaa Energy Booster Capsules",
  "improve metabolism": "La Vedaa Energy Booster Capsules",
  "natural fatigue remedy": "La Vedaa Energy Booster Capsules",
  "low energy solution": "La Vedaa Energy Booster Capsules",
  "herbal immunity booster": "La Vedaa Energy Booster Capsules",
  "boost liver function": "La Vedaa Energy Booster Capsules",
  "mental energy supplement": "La Vedaa Energy Booster Capsules",
  "digestion and energy": "La Vedaa Energy Booster Capsules",
  "workout stamina booster": "La Vedaa Energy Booster Capsules",
  "ayurvedic energy tonic": "La Vedaa Energy Booster Capsules",
  "natural adaptogen": "La Vedaa Energy Booster Capsules",
  "stress and fatigue relief": "La Vedaa Energy Booster Capsules",
  "anti fatigue capsule": "La Vedaa Energy Booster Capsules",
  "herbal revitalizer": "La Vedaa Energy Booster Capsules",
  "herbs for energy": "La Vedaa Energy Booster Capsules",
  "oxygen absorption booster": "La Vedaa Energy Booster Capsules",
  "increase core strength": "La Vedaa Energy Booster Capsules",
  "energy for men and women": "La Vedaa Energy Booster Capsules",
  "non drowsy energy formula": "La Vedaa Energy Booster Capsules",
  "plant based energy pills": "La Vedaa Energy Booster Capsules",
  "hormone balance for vitality": "La Vedaa Energy Booster Capsules",
  "rejuvenation capsules": "La Vedaa Energy Booster Capsules",
  "kesar stamina booster": "La Vedaa Energy Booster Capsules",
  "feel more energetic": "La Vedaa Energy Booster Capsules",
  "herbal workout support": "La Vedaa Energy Booster Capsules",
  "shilajit for energy": "La Vedaa Energy Booster Capsules",
  "ayurvedic shilajit capsule": "La Vedaa Energy Booster Capsules",
  "shilajit stamina booster": "La Vedaa Energy Booster Capsules",
  "natural testosterone support": "La Vedaa Energy Booster Capsules",
  "ashwagandha for stamina": "La Vedaa Energy Booster Capsules",
  "ashwagandha energy capsule": "La Vedaa Energy Booster Capsules",
  "ashwagandha anti-fatigue": "La Vedaa Energy Booster Capsules",
  "salam panja vitality": "La Vedaa Energy Booster Capsules",
  "salam mishri energy benefits": "La Vedaa Energy Booster Capsules",
  "salam panja muscle strength": "La Vedaa Energy Booster Capsules",
  "gokhru for stamina": "La Vedaa Energy Booster Capsules",
  "gokshura testosterone booster": "La Vedaa Energy Booster Capsules",
  "gokhru muscle recovery": "La Vedaa Energy Booster Capsules",
  "giloy for immunity": "La Vedaa Energy Booster Capsules",
  "giloy fatigue relief": "La Vedaa Energy Booster Capsules",
  "ayurvedic giloy supplement": "La Vedaa Energy Booster Capsules",
  "amla for energy": "La Vedaa Energy Booster Capsules",
  "vitamin C herbal supplement": "La Vedaa Energy Booster Capsules",
  "amla immunity booster": "La Vedaa Energy Booster Capsules",
  "triphala for digestion": "La Vedaa Energy Booster Capsules",
  "baheda detox capsule": "La Vedaa Energy Booster Capsules",
  "harad digestion booster": "La Vedaa Energy Booster Capsules",
  "elaichi ayurvedic capsule": "La Vedaa Energy Booster Capsules",
  "arjun heart tonic": "La Vedaa Energy Booster Capsules",
  "arjun for blood flow": "La Vedaa Energy Booster Capsules",
  "arjuna stamina support": "La Vedaa Energy Booster Capsules",
  "ras sindoor vitality": "La Vedaa Energy Booster Capsules",
  "swarnavang ayurvedic energy": "La Vedaa Energy Booster Capsules",
  "ayurvedic nerve strength capsule": "La Vedaa Energy Booster Capsules",
  "pipli for metabolism": "La Vedaa Energy Booster Capsules",
  "sonth anti-inflammatory": "La Vedaa Energy Booster Capsules",
  "kali mirch absorption booster": "La Vedaa Energy Booster Capsules",
  "kesar stamina support": "La Vedaa Energy Booster Capsules",
  "saffron for energy": "La Vedaa Energy Booster Capsules",
  "mood booster kesar": "La Vedaa Energy Booster Capsules",
  "natural blood circulation booster": "La Vedaa Energy Booster Capsules",
  "ayurvedic mood enhancer": "La Vedaa Energy Booster Capsules",
  "stress and stamina support": "La Vedaa Energy Booster Capsules",
  "ayurvedic pre workout": "La Vedaa Energy Booster Capsules",
  "energy capsule for men": "La Vedaa Energy Booster Capsules",
  "energy capsule for women": "La Vedaa Energy Booster Capsules",
  "ayurvedic workout capsule": "La Vedaa Energy Booster Capsules",
  "herbal testosterone support": "La Vedaa Energy Booster Capsules",
  "revitalize body and mind": "La Vedaa Energy Booster Capsules",
  "rejuvenate energy naturally": "La Vedaa Energy Booster Capsules",
  "natural metabolism booster": "La Vedaa Energy Booster Capsules",
  "ayurvedic strength builder": "La Vedaa Energy Booster Capsules",
  "pure herbal stamina capsule": "La Vedaa Energy Booster Capsules",
  "weakness": "La Vedaa Energy Booster Capsules",
"feeling weak": "La Vedaa Energy Booster Capsules",
"tired": "La Vedaa Energy Booster Capsules",
"low energy": "La Vedaa Energy Booster Capsules",

  // Men Care & Energy Booster Combo Pack
  "men combo": "La Vedaa Men Care & Energy Booster Combo Pack",
  "men energy combo": "La Vedaa Men Care & Energy Booster Combo Pack",
  "men care energy": "La Vedaa Men Care & Energy Booster Combo Pack",
  "men full pack": "La Vedaa Men Care & Energy Booster Combo Pack",
  "male combo": "La Vedaa Men Care & Energy Booster Combo Pack",
  "both men energy": "La Vedaa Men Care & Energy Booster Combo Pack",
  "combo for men": "La Vedaa Men Care & Energy Booster Combo Pack",
  "men together pack": "La Vedaa Men Care & Energy Booster Combo Pack",
  "men double pack": "La Vedaa Men Care & Energy Booster Combo Pack",
  "men energy full combo": "La Vedaa Men Care & Energy Booster Combo Pack",
  "complete men pack": "La Vedaa Men Care & Energy Booster Combo Pack",
  "men + energy combo": "La Vedaa Men Care & Energy Booster Combo Pack",
  "all in one men": "La Vedaa Men Care & Energy Booster Combo Pack",

  // Women Care & Energy Booster Combo Pack
  "women combo": "La Vedaa Women Care & La Vedaa Energy Booster Combo Pack",
  "women energy combo": "La Vedaa Women Care & La Vedaa Energy Booster Combo Pack",
  "women care energy": "La Vedaa Women Care & La Vedaa Energy Booster Combo Pack",
  "women full pack": "La Vedaa Women Care & La Vedaa Energy Booster Combo Pack",
  "ladies combo": "La Vedaa Women Care & La Vedaa Energy Booster Combo Pack",
  "both women energy": "La Vedaa Women Care & La Vedaa Energy Booster Combo Pack",
  "combo for women": "La Vedaa Women Care & La Vedaa Energy Booster Combo Pack",
  "women together pack": "La Vedaa Women Care & La Vedaa Energy Booster Combo Pack",
  "female combo pack": "La Vedaa Women Care & La Vedaa Energy Booster Combo Pack",
  "women energy full combo": "La Vedaa Women Care & La Vedaa Energy Booster Combo Pack",
  "complete women pack": "La Vedaa Women Care & La Vedaa Energy Booster Combo Pack",
  "women + energy combo": "La Vedaa Women Care & La Vedaa Energy Booster Combo Pack",
  "all in one women": "La Vedaa Women Care & La Vedaa Energy Booster Combo Pack"
};
